on:
  push:
    branches:
      - master

jobs:
  run_on_ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -G yarn
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: yarn install
      - run: npm run test
      - run: npm start build
  run_on_ubuntu_18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -G yarn
      - run: node --version
      - run: npm --version
      - run: yarn --version
      - run: yarn install
      - run: npm run test
      - run: npm start build
